import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const defaultSidebars: SidebarsConfig = {
  // Default: Automatically generate the sidebar based on the file structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false, 
      items: [{ type: 'autogenerated', dirName: 'overview' }],
    },
    {
      type: 'doc',
      id: 'intro', 
    },
    {
      type: 'doc',
      id: 'data-network', // Direct link to a doc
    },
    {
      type: 'doc',
      id: 'architecture',
    },
    {
      type: 'category',
      label: 'OptimAI Node',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'optimai-node' }],
    },
    {
      type: 'doc',
      id: 'services', // Direct link to a doc
    },
    {
      type: 'doc',
      id: 'optimai-agent', // Direct link to a doc
    },
    {
      type: 'doc',
      id: 'opi-token', // Direct link to a doc
    },
    {
      type: 'doc',
      id: 'roadmap', // Direct link to a doc
    },
    {
      type: 'doc',
      id: 'faqs', // Direct link to a doc
    },
    {
      type: 'category',
      label: 'Resources',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'resources' }],
    },
  ],
};

export default defaultSidebars;
