import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'overview' },
        { type: 'doc', id: 'intro' },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        { type: 'doc', id: 'architecture' },
        { type: 'doc', id: 'data-network' },
        { type: 'doc', id: 'network-operations' },
        { type: 'doc', id: 'services' },
      ],
    },
    {
      type: 'category',
      label: 'Products',
      collapsed: false,
      items: [
        { type: 'doc', id: 'products' },
        { type: 'doc', id: 'optimai-claw' },
        { type: 'doc', id: 'optimai-search' },
        { type: 'doc', id: 'persona-agent' },
        { type: 'doc', id: 'optimai-agent' },
      ],
    },
    {
      type: 'category',
      label: 'OptimAI Nodes',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'optimai-node' }],
    },
    {
      type: 'category',
      label: 'Developers',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'builders' }],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      collapsed: true,
      items: [
        { type: 'doc', id: 'use-cases' },
        { type: 'doc', id: 'opi-token' },
        { type: 'doc', id: 'marketplace' },
        { type: 'doc', id: 'governance-tokenomics' },
        { type: 'doc', id: 'roadmap' },
        { type: 'doc', id: 'litepaper' },
        { type: 'doc', id: 'faqs' },
        { type: 'doc', id: 'changelog' },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'OptimAI Lite Node - Chrome Extension',
          href: 'https://chromewebstore.google.com/detail/optimai-lite-node/njlfcjdojmopagogfpjgcbnpmiknapnd',
        },
        {
          type: 'link',
          label: 'OptimAI Lite Node - Telegram Mini-App',
          href: 'https://t.me/OptimAI_Node_Bot',
        },
        {
          type: 'link',
          label: 'OptimAI Whitepaper',
          href: 'https://optimai.network/files/OptimAI-Whitepaper-v1.pdf',
        },
      ],
    },
  ],
};

export default sidebars;
