import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const defaultSidebars: SidebarsConfig = {
  // Default: Automatically generate the sidebar based on the file structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: true, 
      items: [{ type: 'autogenerated', dirName: 'overview' }],
    },
    {
      type: 'doc',
      id: 'intro', 
    },
    {
      type: 'doc',
      id: 'data-network', // Direct link to a doc
    },
    {
      type: 'doc',
      id: 'architecture',
    },
    {
      type: 'category',
      label: 'OptimAI Node',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'optimai-node' }],
    },
    {
      type: 'doc',
      id: 'services',
    },
    {
      type: 'doc',
      id: 'optimai-agent',
    },
    {
      type: 'doc',
      id: 'opi-token',
    },
    {
      type: 'doc',
      id: 'roadmap', 
    },
    {
      type: 'doc',
      id: 'faqs',
    },
    {
      type: 'doc',
      id: 'litepaper', 
    },
    {
      type: 'category',
      label: 'Resources',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'OptimAI Lite Node - Chrome Extension',
          href: 'https://chromewebstore.google.com/detail/optimai-lite-node/njlfcjdojmopagogfpjgcbnpmiknapnd',
        },
        {
          type: 'link',
          label: 'OptimAI Lite Node - Telegram Mini-App',
          href: 'https://t.me/OptimAI_Node_Bot',
        },
        {
          type: 'link',
          label: 'OptimAI Whitepaper',
          href: 'https://optimai.network/files/OptimAI-Whitepaper-v1.pdf',
        },
      ],
    },
  ],
};

export default sidebars;
